export const BUSINESS_CATEGORIES = [
  "Restaurants",
  "Auto Repair",
  "Hair Salons",
  "Barber Shops",
  "Dentists",
  "Plumbers",
  "Electricians",
  "HVAC Services",
  "Landscaping",
  "Cleaning Services",
  "Pet Grooming",
  "Veterinarians",
  "Bakeries",
  "Coffee Shops",
  "Gyms & Fitness",
  "Yoga Studios",
  "Martial Arts",
  "Chiropractors",
  "Massage Therapy",
  "Accountants",
  "Tax Services",
  "Real Estate Agents",
  "Insurance Agents",
  "Tutoring Services",
  "Music Lessons",
  "Photography Studios",
  "Florists",
  "Dry Cleaners",
  "Nail Salons",
  "Tattoo Shops",
  "Auto Detailing",
  "Towing Services",
  "Moving Companies",
  "Storage Facilities",
  "Dog Training",
  "Day Care",
  "Senior Care",
  "Home Health Care",
  "Legal Services",
  "Notary Services",
];

export const SAN_DIEGO_AREAS = [
  "All San Diego",
  "Downtown San Diego",
  "La Jolla",
  "Pacific Beach",
  "Ocean Beach",
  "Mission Beach",
  "Mission Valley",
  "Hillcrest",
  "North Park",
  "South Park",
  "Gaslamp Quarter",
  "Little Italy",
  "Bankers Hill",
  "University Heights",
  "Normal Heights",
  "Kensington",
  "City Heights",
  "College Area",
  "Clairemont",
  "Kearny Mesa",
  "Mira Mesa",
  "Scripps Ranch",
  "Rancho Bernardo",
  "Carmel Valley",
  "Del Mar",
  "Solana Beach",
  "Encinitas",
  "Carlsbad",
  "Oceanside",
  "Vista",
  "San Marcos",
  "Escondido",
  "Poway",
  "Santee",
  "El Cajon",
  "La Mesa",
  "Lemon Grove",
  "Spring Valley",
  "Chula Vista",
  "National City",
  "Imperial Beach",
  "Coronado",
  "Point Loma",
  "Bay Park",
  "Linda Vista",
];

export const LEAD_STATUSES = [
  { value: "new", label: "New", color: "bg-emerald-500" },
  { value: "contacted", label: "Contacted", color: "bg-cyan-500" },
  { value: "responded", label: "Responded", color: "bg-amber-500" },
  { value: "not_interested", label: "Not Interested", color: "bg-rose-500" },
  { value: "converted", label: "Converted", color: "bg-purple-500" },
];

export const STATUS_COLORS = {
  new: "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
  contacted: "bg-cyan-500/20 text-cyan-400 border-cyan-500/30",
  responded: "bg-amber-500/20 text-amber-400 border-amber-500/30",
  not_interested: "bg-rose-500/20 text-rose-400 border-rose-500/30",
  converted: "bg-purple-500/20 text-purple-400 border-purple-500/30",
};
